# Performing 45 degrees rotation over z axis

In [11]:
import numpy as np
import scipy.special as sp

# Define the rotation angle (45 degrees in radians)
alpha = np.pi / 4

# Wigner D-matrix for l=1 under a rotation about the z-axis by angle alpha
# For l=1, the Wigner D-matrix is a 3x3 matrix
# Since we are rotating about the z-axis, only the diagonal elements are non-zero and are given by e^(-im*alpha)
D = np.diag([np.exp(-1j * (-1) * alpha), np.exp(-1j * 0 * alpha), np.exp(-1j * 1 * alpha)])

# Spherical harmonic Y_10 before rotation (theta = 0 for simplicity)
theta = 0
Y_10_before = np.sqrt(3/(4*np.pi)) * np.cos(theta)

# Transformation of Y_10 under rotation
# For Y_10, we only need the middle row of the D-matrix, which corresponds to m=0
Y_10_after = D[1, :] * Y_10_before

Y_10_after.real  # Taking the real part as the imaginary part should be negligible



array([0.        , 0.48860251, 0.        ])

# Rotating spherical harmonics by 45(theta) and 90 degrees(phi)

In [12]:
import numpy as np

# Define the angles theta and phi
theta = np.pi / 4  # 45 degrees
phi = np.pi / 2    # 90 degrees

# Calculate the original spherical harmonics values
Y_1m_values = {
    -1: np.sqrt(3 / (8 * np.pi)) * np.sin(theta) * np.exp(-1j * phi),
    0: np.sqrt(3 / (4 * np.pi)) * np.cos(theta),
    1: -np.sqrt(3 / (8 * np.pi)) * np.sin(theta) * np.exp(1j * phi)
}

# Define the Wigner D-matrix for l=1 and alpha = pi/4
D_matrix = np.array([
    [np.exp(1j * np.pi / 4), 0, 0],
    [0, 1, 0],
    [0, 0, np.exp(-1j * np.pi / 4)]
])

# Transform the spherical harmonics using the D-matrix
Y_1m_transformed = D_matrix @ np.array(list(Y_1m_values.values()))

# Results
Y_1m_values, Y_1m_transformed.real  # Displaying real parts for simplicity



({-1: (1.4959137556431687e-17-0.24430125595146j),
  0: 0.3454941494713355,
  1: (-1.4959137556431687e-17-0.24430125595146j)},
 array([ 0.17274707,  0.34549415, -0.17274707]))

# 45 degrees rotation over all axes

In [13]:
from scipy.special import sph_harm

# Define the Euler angles for the rotation (alpha, beta, gamma)
alpha = beta = gamma = np.pi / 4  # 45 degrees

# Function to compute the small d-matrix element d^l_m'm for l=1
def d_matrix_element_1(m_prime, m, beta):
    if m_prime == 1 and m == 1:
        return np.cos(beta/2)**2
    elif m_prime == 1 and m == -1:
        return -np.sin(beta/2)**2
    elif m_prime == -1 and m == 1:
        return np.sin(beta/2)**2
    elif m_prime == -1 and m == -1:
        return np.cos(beta/2)**2
    elif m_prime == 0 and m == 1:
        return -np.sqrt(2)/2 * np.sin(beta)
    elif m_prime == 1 and m == 0:
        return np.sqrt(2)/2 * np.sin(beta)
    elif m_prime == 0 and m == -1:
        return -np.sqrt(2)/2 * np.sin(beta)
    elif m_prime == -1 and m == 0:
        return np.sqrt(2)/2 * np.sin(beta)
    elif m_prime == 0 and m == 0:
        return np.cos(beta)
    else:
        return 0

# Compute the Wigner D-matrix for l=1
D_matrix_1 = np.zeros((3, 3), dtype=complex)
for m_prime in range(-1, 2):
    for m in range(-1, 2):
        D_matrix_1[m_prime+1, m+1] = np.exp(-1j * m_prime * alpha) * d_matrix_element_1(m_prime, m, beta) * np.exp(-1j * m * gamma)

# Display the computed Wigner D-matrix for l=1
D_matrix_1



array([[ 0.        +0.85355339j,  0.35355339+0.35355339j,
         0.14644661+0.j        ],
       [-0.35355339-0.35355339j,  0.70710678+0.j        ,
        -0.35355339+0.35355339j],
       [-0.14644661+0.j        ,  0.35355339-0.35355339j,
         0.        -0.85355339j]])

In [14]:
# Calculate the original spherical harmonics values at theta = phi = pi/4
Y_1m_original = np.array([
    sph_harm(-1, 1, phi, theta),
    sph_harm(0, 1, phi, theta),
    sph_harm(1, 1, phi, theta)
])
# Apply the Wigner D-matrix to transform the spherical harmonics
Y_1m_transformed = D_matrix_1 @ Y_1m_original

# Display the original and transformed spherical harmonics values
Y_1m_original, Y_1m_transformed



(array([ 1.49591376e-17-0.24430126j,  3.45494149e-01+0.j        ,
        -1.49591376e-17-0.24430126j]),
 array([ 0.33067479+0.08637354j,  0.24430126+0.17274707j,
        -0.08637354-0.08637354j]))

# Reducible representations

# Irreducible representations of a group

In [15]:
import numpy as np

# Define the rotation matrices for SO(3) group, rotation around the z-axis
D_e = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
D_r90 = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
D_r180 = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])
D_r270 = np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]])

# Inversion matrix for O(3) group
D_I = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])

# Group operation: combining a 180-degree rotation and inversion
D_r180_I = D_r180 @ D_I

# Display the matrices and the result of their group operation
D_e, D_r90, D_r180, D_r270, D_I, D_r180_I



(array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]),
 array([[ 0, -1,  0],
        [ 1,  0,  0],
        [ 0,  0,  1]]),
 array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1]]),
 array([[ 0,  1,  0],
        [-1,  0,  0],
        [ 0,  0,  1]]),
 array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0, -1]]),
 array([[ 1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0, -1]]))